// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZi-kNPaSfjvevmRbwpdDRpnCYPeSKdM',
    appId: '1:758810139442:web:5bff9b70b4b39f5c89152b',
    messagingSenderId: '758810139442',
    projectId: 'lucid-authority-365519',
    authDomain: 'lucid-authority-365519.firebaseapp.com',
    storageBucket: 'lucid-authority-365519.appspot.com',
    measurementId: 'G-3XGVL1FPS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPEXtOEaG8VnlINYrPadIhCJLV8BZn7D4',
    appId: '1:758810139442:android:86fe5604170a234d89152b',
    messagingSenderId: '758810139442',
    projectId: 'lucid-authority-365519',
    storageBucket: 'lucid-authority-365519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd4q3SW3BaNXbnhzuxZIZavgaGSnPfyvE',
    appId: '1:758810139442:ios:90973952a96e24de89152b',
    messagingSenderId: '758810139442',
    projectId: 'lucid-authority-365519',
    storageBucket: 'lucid-authority-365519.appspot.com',
    iosClientId: '758810139442-7i4gjp7so90i57aalq7gp6m9b9ac67lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenOrdinario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd4q3SW3BaNXbnhzuxZIZavgaGSnPfyvE',
    appId: '1:758810139442:ios:90973952a96e24de89152b',
    messagingSenderId: '758810139442',
    projectId: 'lucid-authority-365519',
    storageBucket: 'lucid-authority-365519.appspot.com',
    iosClientId: '758810139442-7i4gjp7so90i57aalq7gp6m9b9ac67lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenOrdinario',
  );
}
